Imp_SQL = [
    "delete from T_MI_COUNTERPARTIES a where a.code like 'test%' ",
    "delete from T_MI_PAYMENTS where SRCBATCHNO like 'txb%' ",
    "delete from T_MI_RECMENTS where SRCBATCHNO like 'txb%' ",
    "delete from T_MI_BANKLOANS where SRCSERIALNO like 'txbFLSQ01%' ",
    "delete from t_mi_foreignpayments where SRCBATCHNO like 'test%' ",
    "delete from T_MI_PAYMENTDETAIL where srcnotecode like 'zy333001' ",
    "delete from T_MI_BANKACCOUNTAPPLY a where a.SRCBATCHNO like 'txb%' ",
    "delete from T_MI_VOUCHERBALANCES  t where SRCSERIALNO like 'txb%' ",
    "delete from T_MI_DRAFTJOURNALS t where SRCSERIALNO like'txb%' ",
    "delete from T_MI_COUNTERPARTIES a where a.code like 's011%' ",
    "delete from T_MI_COUNTERPARTYACCOUNTS t where t.COUNTERPARTYCODE in(select code from T_MI_COUNTERPARTIES a where a.code like 's011%') ",
    "delete from T_MI_PAYMENTS where SRCBATCHNO like 'txbPMSQ03_JN%' ",
    "delete from T_MI_PAYMENTEXCHANGEEXT where SRCSERIALNO in(select SRCSERIALNO from T_MI_PAYMENTS where SRCBATCHNO like 'txbPMSQ03_JN%') ",
    "delete from T_MI_PAYMENTEXCHANGEEXT a where a.srcserialno like 'testbPMSQ03_JN%' ",
    "delete from T_MI_PAYMENTS where SRCBATCHNO like 'txbPMSQ03_KJ%' ",
    "delete from T_MI_PAYMENTEXCHANGEEXT where SRCSERIALNO in(select SRCSERIALNO from T_MI_PAYMENTS where SRCBATCHNO like 'txbPMSQ03_KJ%') ",
    "delete from T_MI_PAYMENTEXCHANGEEXT a where a.srcserialno like 'testbPMSQ03_KJ%' ",
    "delete from T_MI_PAYMENTS where SRCBATCHNO like 'txbPMSQ03_QQ%' ",
    "delete from T_MI_PAYMENTEXCHANGEEXT where SRCSERIALNO in(select SRCSERIALNO from T_MI_PAYMENTS where SRCBATCHNO like 'txbPMSQ03_QQ%') ",
    "delete from T_MI_PAYMENTEXCHANGEEXT a where a.srcserialno like 'testbPMSQ03_QQ%' ",
    "delete from imp.t_mi_implocinssueapply t where t.srcbatchno like 'txbLCSQ01%' ",
    "delete from T_MI_PAYDRAFTS a where a.DRAFTCODE like 'testRDSQ04%' ",
    "delete FROM T_MI_THIRDPARTYRECMENTS T WHERE SRCNOTECODE like 'testESTPSB01%' and SRCBATCHNO like 'txbESTPSB01%' ",
    "delete from T_MI_RECMENTS where orgcode='001000' and SRCBATCHNO like 'txbRMSQ01_SK%' ",
    "delete from T_MI_JOURNALS where ORGCODE = '001000' and urid like 'txbJNSQ01%' ",
    "delete from T_MI_BUDGETADJUSTS  a where a.BUDGETCODE like 'ZJJH_001000_test004%' and a.SRCNOTECODE like 'txbBUSQ02%' ",
    "delete from T_MI_BUDGETS  a where a.SRCNOTECODE like 'txbBUSQ01%' ",
    "delete from T_MI_IMPLETTEROFCREDITS a where a.srcserialno like 'Felix2021040811005' "
]

Mai_SQL = [
    "delete from T_SE_COUNTERPARTIES where code like 'test%' ",
    "delete from T_FL_BANKLOANREPAYS a where a.principal like '9850820' ",
    "delete from T_FL_LOANLENDS a where a.lendamount like '19850820' ",
    "delete from T_FL_BANKLOANS where contractcode like'testFLSQ01%' ",
    "delete from t_se_journals where urid like 'txb%' ",
    "delete from T_EI_UNIQUEKEYS a where a.keycode like 'test%' ",
    "delete from T_CF_FORECASTORIGINAL t where AMOUNT='19850820.11' ",
    "delete from T_CF_FORECASTDATAS t where AMOUNT='19850820.11' ",
    "delete from T_SE_PAYMENTDETAIL where paymentid=(select urid from  T_SE_PAYMENTS where SRCNOTECODE='zy333001') ",
    "delete from T_BA_ACCOUNTAPPLIES where SRCBATCHNO like 'txb%' ",
    "update T_BI_EXPLETTEROFCREDITS t set t.CLAIMNOTE=null,t.CLAIMSTATE=1,t.CLAIMANT=null,t.CLAIMDATE=null,t.GENERATEPAYMENTSTATE=1 where CREDITNUMBER='CKXYZ001' ",
    "delete from T_GL_VOUCHERBALANCES where SOURCEID like 'txb%' ",
    "delete from T_SE_COUNTERPARTYACCOUNTS t where t.COUNTERPARTYID in(select urid from T_SE_COUNTERPARTIES a where a.code like 's011%') ",
    "delete from T_SE_COUNTERPARTIES where code like 's011%' ",
    "delete from T_SE_PAYMENTEXCHANGEEXT a where a.paymentid in (select t.urid from T_SE_PAYMENTS t where t.srcbatchno like 'txbPMSQ03_JN%') ",
    "delete from T_SE_PAYMENTS t where t.srcbatchno like 'txbPMSQ03_JN%' ",
    "delete from T_EI_UNIQUEKEYS a where a.keycode like 'txbPMSQ03_JN%' ",
    "delete from T_SE_PAYMENTEXCHANGEEXT a where a.paymentid in (select t.urid from T_SE_PAYMENTS t where t.srcbatchno like 'txbPMSQ03_KJ%') ",
    "delete from T_SE_PAYMENTS t where t.srcbatchno like 'txbPMSQ03_KJ%' ",
    "delete from T_EI_UNIQUEKEYS a where a.keycode like 'txbPMSQ03_KJ%' ",
    "delete from T_SE_PAYMENTEXCHANGEEXT a where a.paymentid in (select t.urid from T_SE_PAYMENTS t where t.srcbatchno like 'txbPMSQ03_QQ%') ",
    "delete from T_SE_PAYMENTS t where t.srcbatchno like 'txbPMSQ03_QQ%' ",
    "delete from T_EI_UNIQUEKEYS a where a.keycode like 'txbPMSQ03_QQ%' ",
    "delete from t_bi_implocinssueapply t where t.srcbatchno like 'txbLCSQ01%' ",
    "delete from T_EI_UNIQUEKEYS a where a.keycode like 'txbLCSQ01%' ",
    "delete FROM T_BI_PAYDRAFTS A WHERE A.DRAFTCODE like 'testRDSQ04%' ",
    "delete from T_EI_UNIQUEKEYS a where a.keycode like 'txbESTPSB01%' ",
    "delete FROM T_TPP_RECMENTEXT a WHERE a.Recmentid in (SELECT urid FROM T_TPP_RECMENTS WHERE SRCNOTECODE like 'testESTPSB01%') ",
    "delete FROM T_TPP_RECMENTS WHERE SRCNOTECODE like 'testESTPSB01%' ",
    "update T_BA_BANKDAYBOOKS t set t.CLAIMSTATE=2,PAYMENTGENERATESTATE=2 where URID='6dacabcb3cc24a2bb6efda54a76ac03b' ",
    "update T_SE_RECMENTS t set t.CANCELSTATE=1 where T.NOTECODE='ZJSK_001000_202104_00000026' ",
    "delete from T_EI_UNIQUEKEYS a where a.keycode like 'txbBASQ03%' ",
    "delete FROM T_SE_RECMENTDETAIL WHERE RECMENTID='16910ccb83f5499c8a99021d709bddbb' ",
    "delete FROM T_SE_PAYMENTS T WHERE T.NOTECODE in(SELECT t.notecode FROM T_BA_BANKDAYBOOKS t WHERE URID='6a56ddb817714c71b381f1740e8851e1') ",
    "update T_BA_BANKDAYBOOKS t set t.CLAIMNOTE=null,t.CLAIMSTATE=1,t.CLAIMANT=null,t.CLAIMDATE=null,PAYMENTGENERATESTATE=1,notecode=null where URID='6a56ddb817714c71b381f1740e8851e1' ",
    "delete FROM T_SE_RECMENTS T WHERE T.NOTECODE in(SELECT t.notecode FROM T_BA_BANKDAYBOOKS t WHERE URID='149624a4d5924f0e837b0237ea87d9e4') ",
    "update T_BA_BANKDAYBOOKS t set t.CLAIMNOTE=null,t.CLAIMSTATE=1,t.CLAIMANT=null,t.CLAIMDATE=null,PAYMENTGENERATESTATE=1,notecode=null where URID='149624a4d5924f0e837b0237ea87d9e4' ",
    "delete from T_SE_RECMENTS a where a.srcbatchno like 'txbRMSQ01_SK%' ",
    "delete from T_EI_UNIQUEKEYS a where a.keycode like 'txbRMSQ01_SK%' ",
    "delete from T_SE_JOURNALS where ORIGINNOTE ='ZJFK_001000_202104_00001014' ",
    "update T_SE_PAYMENTS t set t.paystate=2 where t.notecode = 'ZJFK_001000_202104_00001014' ",
    "delete from T_BI_RECDRAFTSEXTEND a where a.purid like 'txbRDSQ01%' ",
    "delete from T_BI_RECDRAFTS where DESCRIPTION = '描述111' ",
    "delete from T_BI_RECCHEQUES t where t.oppname = 'Mindy自动化测试' and t.urid like 'txbCBSQ01%' ",
    "delete from T_BU_BUDGETADJUSTDETAILS where budgetadjustid=(select urid from T_BU_BUDGETADJUSTS where sourceid like 'txbBUSQ02%') ",
    "delete from T_BU_BUDGETADJUSTS where sourceid like 'txbBUSQ02%' ",
    "delete from T_BU_BUDGETDETAILS where budgetid=(select urid from T_BU_BUDGETS WHERE SOURCEID like 'txbBUSQ01%') ",
    "delete from T_BU_BUDGETS WHERE SOURCEID like 'txbBUSQ01%' ",
    "delete from T_BI_IMPLETTEROFCREDITOPS a where a.LETTEROFCREDITID in (select a.urid from T_BI_IMPLETTEROFCREDITS a where a.creditnumber like 'Felix2021040811005') ",
    "delete from T_BI_IMPLETTEROFCREDITS a where a.creditnumber like 'Felix2021040811005' ",
    "update T_BI_RECDRAFTOPERATIONS t set t.generatepaymentstate='1' ,t.claimstate='1' where t.DRAFTID in (select t.draftid from T_BI_RECDRAFTOPERATIONS t where DRAFTID in (select t.urid from T_BI_RECDRAFTS t where DRAFTCODE = 'mmm2345678')) ",
    "update T_BI_ELEDRAFTOPERATIONS t set t.generatepaymentstate='1',t.claimstate='1' where t.DRAFTID = '611ab827b6d145888bcd8575532c16a6' and t.Operateflag='2003'and t.TRANSSTATE='2' ",
    "delete from T_SE_PAYMENTS where SRCSERIALNO like 'test%' ",
    "delete from t_ei_uniquekeys t where t.keycode like 'txb%' "
]
